name: CMake

on:
  push:
    branches:
      - master
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-18.04, CC: gcc-7, CXX: g++-7 }
          - { os: ubuntu-18.04, CC: clang-5.0, CXX: clang++-5.0 }
          - { os: ubuntu-18.04, CC: clang-9, CXX: clang++-9 }
          - { os: ubuntu-20.04, CC: gcc-7, CXX: g++-7 }
          - { os: ubuntu-20.04, CC: clang-8, CXX: clang++-8 }
          - { os: ubuntu-20.04, CC: gcc-10, CXX: g++-10 }
          - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12 }
          - { os: macOS-latest, CC: clang, CXX: clang++ }
          # - { os: windows-latest, CC: gcc, CXX: g++ }

    steps:
    - uses: actions/checkout@v3
    
    - name: Install compiler
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install ${{ matrix.config.CC }} ${{ matrix.config.CXX }}
         fi
      shell: bash

    - name: Configure CMake
      env:
        CC: ${{ matrix.config.CC }}
        CXX: ${{ matrix.config.CXX }}
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      env:
        CC: ${{ matrix.config.CC }}
        CXX: ${{ matrix.config.CXX }}
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      env:
        CC: ${{ matrix.config.CC }}
        CXX: ${{ matrix.config.CXX }}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cd ${{github.workspace}}/build && make unittest && test/unittest
      
